# ch8 예외처리

## 예외처리(exception handling)

### 1.1. 프로그램 오류

- 프로그램 에러/오류: 프로그램이 실행 중 어떤 원인에 의해 오작동을 하거나 비정상적으로 종료되는 경우를 초래하는 원인
- 발생 시점에 따라 컴파일 에러(compile-time-error) / 런타임 에러(runtime error)로 나뉨
- 컴파일 에러: 컴파일할 때 발생하는 에러
- 런타임 에러: 프로그램의 실행 도중 발생하는 에러
- 논리적 에러(logical error): 컴파일도 잘 되고 실행도 잘 되지만 의도한 것과 다르게 동작하는 것
- 소스코드를 컴파일 시 컴파일러가 소스코드(*.java)에 대해 오타나 잘못된 구문, 자료형 체크 등 기본적인 검사를 수행해 오류가 있는지를 알려줌
- 컴파일러가 알려준 에러들을 모두 수정해 컴파일을 성공적으로 마치면 클래스 파일(*.class)이 생성되고 생성된 클래스 파일 실행이 가능해짐
- 컴파일러가 기본적인 에러는 걸러주지만, 실행 도중 발생하는 잠재적인 오류까지 검사할 수 없어 컴파일은 잘 돼도 실행 중 에러에 의해 잘못된 결과를 얻거나 프로그램이 비정상 종료될 수 있음
- 자바는 실행 시(runtime) 발생할 수 있는 프로그램 오류를 에러(eroor) / 예외(exception)로 구분
- 에러: 메모리 부족(OutOfMemoryError)이나 스택오버플로우(StackOverflowError) 같이 일단 발생하면 복구 불가 심각한 오류
- 예외: 발생하더라도 수습가능한 다소 미약한 오류
- 에러 발생 시, 프로그램의 비정상적인 종료를 막을 수 없지만 예외는 발생해더 프로그래머가 이에 대한 적절한 코드를 미리 작성함으로써 프로그램의 비정상적인 종료를 막을 수 있음

### 1.2. 예외 클래스의 계층 구조

- 자바는 실행 시 발생할 수 있는 오류(Exception / Error)를 클래스로 정의
- 모든 클래스의 조상은 Object 클래스로 Exception / Error 클래스는 Object 클래스의 자손들로 존재
- 모든 예외의 최고 조상은 Exception 클래스

#### 예외 클래스의 나눠지는 두 그룹

1. Exception클래스와 그 자손들
2. RuntimeException클래스와 그 자손들

- RuntimeException 클래스들은 주로 프로그래머의 실수에 의해 발생될 수 있는 예외들로 자바 프로그램 요소들과 관계가 깊음
*예: 배열의 범위 벗어남(ArrayIndexOutOfBoundsException), 값이 null인 참조변수의 멤버를 호출(NullPointerException), 클래스 간 형변환 실수(ClassCastException), 정수를 0으로 나누려는 것(ArithmeticException)하는 경우*
- Exception클래스들은 주로 외부 영향으로 발생할 수 있는 것들로, 프로그램의 사용자들 동작에 의해 발생되는 경우가 많음
*예: 존재하지 않는 파일의 이름 입력(FileNotFoundException), 실수로 클래스의 이름을 잘못 적음(ClassNotFoundException), 입력 데이터 형식이 잘못됨(DataFormatException)*
- Exception클래스들: 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외
- RuntimeException클래스들: 프로그래머의 실수로 발생하는 예외

### 1.3. 예외처리하기 - try-catch문

- 예외처리(exception handling): 프로그램 실행 시 발생할 수 있는 예기치 못한 예외의 발생에 대비한 코드를 작성하는 것
- 예외처리 목적: 예외의 발생으로 인한 실행 중인 프로그램의 갑작스런 비정상 종료를 막고, 정상적인 실행상태를 유지할 수 있도록 하는 것
- 발생한 예외를 처리하지 못할 시, 프로그램은 비정상적 종료로 처리되지 못한 예외(uncaught exception)는 JVM의 예외처리기(UncaughtExceptionHandler)가 받아 예외의 원인을 화면에 출력
- 예외를 처리하기 위해 try-catch문 사용
- 하나의 try블럭 다음에 여러 종류의 예외를 처리할 수 있도록 하나 이상의 catch블럭이 올 수 있으며, 이 중 발생한 예외의 종류와 일치하는 단 한 개의 catch 블럭만 수행되며, 발생한 예외의 종류와 일치한느 catch블럭이 없으면 예외 처리되지 않음
*if문과 달리 try블럭이나 catch 블럭 내 포함된 문장이 하나뿐이여도 괄호{} 생략 불가*
- catch 블럭 내 또 하나의 try-catch문이 포함된 경우, 같은 이름의 참조변수를 사용해서는 안됨
- 각 catch블럭에 선언된 두 참조변수의 영역이 서로 겹치므로 다른 이름을 사용해 서로 구별하게 해야함

### 1.4. try-catch문에서의 흐름

- 예외가 발생한 경우와 발생하지 않았을 때의 흐름(문장의 실행순서)이 달라짐

#### 두 가지 경우에 따른 문장 실행순서 정리

##### try블럭 내에서 예외가 발생하는 경우

1. 발생한 예외와 일치하는 catch 블럭이 있는지 확인
2. 일치하는 catch블럭을 찾을 시, 그 catch블럭 내 문장들을 수행하고 전체 try-catch문을 빠져나와서 그 다음 문장을 계속해서 수행하며, 만약 일치하는 catch블럭을 찾지 못하면, 예외는 처리 불가

##### try블럭 내에서 예외가 발생하지 않은 경우

1. catch 블럭을 거치지 않고 전체 try-catch문을 빠져나와 수행을 계속함

- try 블럭에서 예외가 발생 시, 예외가 발생한 위치 이후에 있는 try 블럭의 문장들은 수행되지 않으므로, try 블럭에 포함시킬 코드의 범위를 잘 선택해야함

### 1.5. 예외의 발생과 catch 블럭

- catch 블럭은 괄호()와 블럭{} 두 부분으로 나눠져있는데, 괄호() 내에는 처리하고자 하는 예외와 같은 타입의 참조변수 하나 선언 필요
- 예외 발생 시, 발생한 예외에 해당하는 클래스의 인스턴스가 생성
- 첫 번째 catch 블럭부터 하나씩 차례로 내려가며 catch 블럭의 괄호() 내에 선언된 참조변수의 종류와 생성된 예외클래스의 인스턴스에 instanceof 연산자를 이용해 검사하는데, 검사 결과가 true인 catch 블럭을 만날 때까지 검사가 계속됨
- 검사 결과가 true인 catch 블럭을 찾을 시 블럭에 있는 문장들을 모두 수행 후 try-catch문을 빠져나가고 예외는 처리되나, 검사 결과가 true인 catch블럭이 하나도 없으면 예외 처리 불가
- 모든 예외 클래스는 Exception클래스의 자손으로 catch 블럭의 괄호()에 Exception클래스 타입의 참조변수를 선언해놓으면 어떤 종류의 예외가 발생해도 catch블럭에 의해 처리

#### printStackTrace()와 getMessage()

- 예외 발생 시 생성되는 예외 클래스의 인스턴스에는 발생한 예외에 대한 정보가 있으며 printStackTrace()와 getMessage()를 통해 정보 획득 가능
- catch 블럭의 괄호()에 선언된 참조변수를 통해 이 인스턴스에 접근 가능
- 이 참조변수는 선언된 catch블럭 내에서만 사용 가능

##### 자주 사용되는 메서드

- printStackTrace(): 예외 발생 당시 호출스택(Call Stack)에 있었던 메서드 정보와 예외 메시지를 화면에 출력
- getMessage(): 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있음